fix: remove failing and unused repository
The repo gives
Error: looks like "https://kubernetes-charts.banzaicloud.com" is not a valid chart repository or cannot be reached: Get "https://kubernetes-charts.banzaicloud.com/index.yaml": x509: certificate has expired or is not yet valid: current time 2022-12-19T08:18:17Z is after 2022-12-19T07:42:55Z